name: Only-Workflow-Changes

# Trigger dev deployment on only from master branch or only with specific tags.
on: 
  push:
    paths:
        - '.github/workflows/**'
      
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Workflow related pushes
        run: |
            echo "No Server Deployment needed, only workflow related changes. "
        
